<a href="https://colab.research.google.com/github/redboycode/udemycourses/blob/main/lazy_prog_numpy/Numpy_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arrays vs Lists

In [1]:
import numpy as np

In [14]:
L = [1,2,3]

In [6]:
A = np.array([1,2,3])

In [7]:
for e in L:
  print(e)

1
2
3


In [8]:
for e in A:
  print(e)

1
2
3


In [15]:
L.append(4)

In [16]:
L

[1, 2, 3, 4]

In [12]:
A.append(4) #wont work because no append function

AttributeError: ignored

In [17]:
L + [5] #append or concatenate to list 

[1, 2, 3, 4, 5]

In [19]:
A + np.array([4]) #broadcasting, instead of appending it adds 4 to same element
# a + operation in numpy does a math operation

array([5, 6, 7])

In [20]:
A+np.array([4,5,6])

array([5, 7, 9])

In [21]:
A+np.array([4,5]) # cant add vector of different sizes since A = 1,2,3

ValueError: ignored

In [22]:
2* A

array([2, 4, 6])

In [23]:
2 * L # for list multiply does repetition, for array above it does piecewise multiplication

[1, 2, 3, 4, 1, 2, 3, 4]

In [24]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [25]:
#to add a 3 to each element in List L
L2 = []
for e in L:
  L2.append(e+3)

In [26]:
L2 # 3 added to each element

[4, 5, 6, 7]

In [28]:
L2 = [e + 3 for e in L] # list comprehension, the other way to do the above
L2

[4, 5, 6, 7]

In [29]:
L**2 #wont work, instead to each wise

TypeError: ignored

In [30]:
L2= []
for e in L:
  L2.append (e**2)
L2

[1, 4, 9, 16]

In [31]:
A**2 #in numpy though , if you apply an operation it often goes element wise
#from here on you'll see all these methods do elementwise calc, something you cant do in LISTS

array([1, 4, 9])

In [32]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [33]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [35]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [36]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

# The Dot Product